apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: httpd:latest
          name: httpd
          # command: ["/bin/bash", "-c"] # override the default command
          # args: ["sleep 5; exit 1"] # sleep for 30 seconds then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Maximum number of pods that can be created over the desired number of pods
      maxUnavailable: 1 # Maximux number od pods that can be unavailable during the update process